postgres:
  image: postgres:9.5.1
opennms:
  build: opennms
  ports:
   - "18101:8101"
   - "18980:8980"
  # Work around for too many files issue when running the Liquibase migrations
  privileged: true
  ulimits:
    nofile:
      soft: 40000
      hard: 80000
  links:
   - postgres
minion:
  build: minion
  ports:
   - "28101:8201"
   - "1514:1514/udp"
  links:
   - opennms
